### ISSUE TITLE
When using mailto tag, if message body is > 1500 characters, warn of potential issues (see issue #97)

### ISSUE THREAD

**Issue by timsenger** [AbundantCommunities/CommonGood#101]
When the mailto: tag body content exceeds around 1500 characters:
- Chrome/Win8.1: the mail client is not invoked to create new message
- Firefox/Win8.1: the mail client is invoked, but the body in the new message is truncated

**Comment by timsenger** [comment]
Consider presenting modal when mailto body is > 1500 characters. Include a "Don't warn me again." checkbox that is stored as persistent cookie. That way for browsers/platforms that do not exhibit the issue, users can click the checkbox to suppress. Might need a way to later turn off the checkbox.

Another approach is to have Javascript check user agent and present modal only if on browser/platform that exhibits the problem. Less appealing because developers have to test all browser/OS combinations (as new versions released) and update code.

**Comment by cognish** [comment]
We now rely on user copy+paste to send emails. This problem is no longer an issue.
