### ISSUE TITLE
Email stuff in new browser tab (re Gmail)

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#103]
When I display search results' "Contact Info" and select "Email Contact List", gmail fires up in the same tab as the CG webapp; this is not obvious (and feels wrong). After sending the email, I have to remember to use backspace to get back to our webapp.

Is there a way to force gmail to run in a new tab (not sure how mailto works in the different o/systems)?

**Comment by timsenger** [comment]
I will look into this. Some info here:

http://stackoverflow.com/questions/11576255/how-to-open-mailto-links-in-new-tab-for-users-that-have-gmail-as-the-default-mai

**Comment by cognish** [comment]
Since we switched to using copy+paste for emails, this is no longer an issue.
