### ISSUE TITLE
Notes (etc) longer than 255 characters blow up

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#107]
If you try to save a string longer than 255 characters into a row's notes field, you generate an org.postgresql.util.PSQLException with message = "ERROR: value too long for type character varying(255)".

This problem applies to other character-based fields, like family name, block description, etc. Two issues:
1. perhaps changing the database schema to allow longer (shorter?) lengths
2. enforcing this in the browser

**Comment by cognish** [comment]
Also, see #129.

**Comment by timsenger** [comment]
Added length check to various views.
