### ISSUE TITLE
Answer text longer than 1,000 characters blows up

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#129]
This is not like postgres generating "spi.SqlExceptionHelper  - ERROR: value too long for type character varying(255)". The error does not appear to reach postgres. The error is "grails.validation.ValidationException: Validation Error(s) occurred during save()".

We have a grails constraint, "text( maxSize:1000 )", but we don't use that to help the user! We're simply throwing a non-postgres exception.

**Comment by cognish** [comment]
Also, see #107.

**Comment by timsenger** [comment]
Added length check in view question/index.gsp.
