### ISSUE TITLE
Use a DELETE request to delete a DA record for a BC

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#15]
Currently we're using a GET.

**Comment by timsenger** [comment]
Changed method to DELETE in gsp.
Can now specify allowed methods in controller (AuthorizationController.groovy).

**Comment by cognish** [comment]
Fascinating: I tried to enforce DELETE with allowedMethods but it kept failing. Turns out DELETE is defined in the HTTP standard. The _HTML_ standard for form elements allows only GET and POST!

We now use POST.

**Comment by cognish** [comment]
p.s., Ajax can use all the HTTP verbs
