### ISSUE TITLE
Implement delete of family

### ISSUE THREAD

**Issue by timsenger** [AbundantCommunities/CommonGood#35]
Prevents deletion if any family member person records have a domain_authorization record.
Also deletes all answer records of all family members of family.
Also deletes all family member person records of family.

**Comment by cognish** [comment]
re "Prevents deletion if any family member person records have a domain_authorization record." How about we simply delete the DA record?

**Comment by cognish** [comment]
Noted while manually deleting person rows (on BD NC's request): in this request, the two people belonged to the same family and one of the people was the interviewer of the family -- caused a FK integrity stumble.

**Comment by cognish** [comment]
Done!
