### ISSUE TITLE
Make search results email-able

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#52]
Example: search for "mental health" gives us a list of person names. Would be handy if user could choose to expand this to include: address, email address & phone number (and exact answer and date of interview).

Copy and paste to an email -- or print web page.

**Comment by cognish** [comment]
Let's do: two views, today's view plus a contact-list-type view; in the contact-list view add a "email" option (body only)

**Comment by cognish** [comment]
Enhanced SearchController & SearchService. Now: search/withContactInfo returns search results with personal contact info.

**Comment by timsenger** [comment]
Implemented email using HTML mailto: in search/withContactInfo.
