### ISSUE TITLE
Support approximate birthYear

### ISSUE THREAD

**Issue by cognish** [AbundantCommunities/CommonGood#7]
Marie-Danielle says that not only are some adults uncomfortable giving their birth year, some BCs are uncomfortable asking. She relates that she will sometimes judge someone to be, let's say, in their 50's and calculate a birth year. "It's 2015, this person is in his 50's, I'll record 1960 as his birth year."

**Comment by cognish** [comment]
At the 2016.2.13 NC meeting at Howard's place, one NC (Linda?) made a helpful suggestion: BC calculates an estimated birth year by guessing the age. Should we flag such birth year guesses?

**Comment by cognish** [comment]
As of NC meeting at Howard's place, 2016.3.12, we have general agreement that we keep birthYear and add a flag to signal "approximate birth year".

**Comment by timsenger** [comment]
[This commit](https://github.com/AbundantCommunities/CommonGood/commit/e3bbfc80fc0804f74a1b090baa3654ede4789b60) pushed implementation of exposing "estimated" birth year in UI along with enabling entry of either birth year or age. Related features, like displaying age on search results, will be entered as separate issues.
