### ISSUE TITLE
Investigate "Email Contact List" on platform Win10+Chrome (latest)

### ISSUE THREAD

**Issue by timsenger** [AbundantCommunities/CommonGood#97]
Simple mailto: link that populates to: address works, but Email Contact List, which constructs a text string and populates message body does not.

**Comment by timsenger** [comment]
Discovered a limitation in the mailto: tag for Firefox and Chrome on Win8 (likely also Win10). Not sure if this is a browser issue (more likely) or the OS mechanism used to pass the mailto: tag value from the browser to the resident mail client (less likely).

When the mailto: tag exceeds around 1500 characters:
- Chrome: the mail client is not invoked to create new message
- Firefox: the mail client is invoked, but the body in the new message is truncated

Raises the importance of issue #79.

**Comment by cognish** [comment]
Should CG measure length of mailto: and warn if > 1500 characters?

**Comment by timsenger** [comment]
Good idea. Will create new issue.
